services:
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    restart: unless-stopped
    networks:
      - fm2c-net

  fm2c-api:
    image: registry.scch.at/humace/spl-visualizer-api:latest
    container_name: fm2c-api
    restart: unless-stopped
    ports:
      - "85:8787"
    environment:
      VALKEY_URL: redis://valkey:6379
    volumes:
      - fm2c-data:/app/data
      - fm2c-workspaces:/app/generated-workspaces
      - fm2c-dist:/app/generated-dist
    networks:
      - fm2c-net
    depends_on:
      - valkey

  fm2c-worker:
    image: registry.scch.at/humace/spl-visualizer-worker:latest
    env_file:
      - .env
    container_name: fm2c-worker
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      VALKEY_URL: redis://valkey:6379
      VALKEY_HOSTNAME: valkey
      OPENAI_BASE_URL: https://api.openai.com/v1
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - fm2c-data:/app/data
      - fm2c-workspaces:/app/generated-workspaces
      - fm2c-dist:/app/generated-dist
    networks:
      - fm2c-net
    depends_on:
      - valkey

networks:
  fm2c-net:
    name: fm2c-net

volumes:
  fm2c-data:
  fm2c-workspaces:
  fm2c-dist:
